version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    container_name: patient-risk-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=outputs/model.pkl
      - PREPROCESSOR_PATH=outputs/preprocessor.joblib
      - DB_URI=sqlite:///data/patient_data.db
      - PORT=8000
    volumes:
      - .:/app
    restart: always

  dashboard:
    build:
      context: .
      dockerfile: src/dashboard/Dockerfile
    container_name: patient-risk-dashboard
    command: streamlit run src/dashboard/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_ENDPOINT=http://api:8000/predict
    volumes:
      - .:/app
    restart: always
